sudo: false
language: python
branches:
  only:
    - master
install:
  - pip install -q $DJANGO
  - pip install -e .
  - pip install coveralls
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - "pypy"
  - "pypy3"
env:
  - DJANGO="Django>=1.11,<2.0"
  - DJANGO="Django>=2.0,<2.1"
  - DJANGO="Django>=2.1,<2.2"
matrix:
  exclude:
    - python: 2.7
      env: DJANGO="Django>=2.0,<2.1"
    - python: "pypy"
      env: DJANGO="Django>=2.0,<2.1"
    - python: 2.7
      env: DJANGO="Django>=2.1,<2.2"
    - python: 3.4
      env: DJANGO="Django>=2.1,<2.2"
    - python: "pypy"
      env: DJANGO="Django>=2.1,<2.2"
script:
  - coverage run --source django_social_share setup.py test
after_success:
  coveralls
